### ISSUE TITLE
Qubes Windows Tools Uninstallable

### ISSUE THREAD

**Issue by e6lk7dqzm83p** [Qubes-Community/Contents#146] opened 2021-09-24 17:09 UTC
Hi,

Neither of these following commands work (am currently on the R4.1 Beta):

`sudo qubes-dom0-update qubes-windows-tools`
`sudo qubes-dom0-update --enablerepo=qubes-dom0-current-testing qubes-windows-tools`

I get the following output:

> No Match for argument qubes-windows-tools
Nothing to download
Fetching updates failed with code 1; press Enter to exit

This precludes the excellent tool for managing windows by @elliotkillick from working.

**Comment by e6lk7dqzm83p** [comment] 2021-09-25 01:29
@andrewdavidwong, I don't know if this is maybe an R4.1 Beta issue?

**Comment by andrewdavidwong** [comment] 2021-09-25 06:14
Hmm... This *might* turn out to be a duplicate of #1861, #3585, and/or #6289, but it is not immediately obvious to me that this is identical to any of them, so I'll leave it open.

**Comment by andrewdavidwong** [comment] 2021-09-25 06:14
Oh, wait, this is Qubes-Community, lol! Deleting.

**Comment by andrewdavidwong** [comment] 2021-09-25 06:16
> @andrewdavidwong, I don't know if this is maybe an R4.1 Beta issue?

I don't know the answer, but you might want to have a look at these:

https://qubes-os.discourse.group/t/windows-support-in-qubes/4288/
https://github.com/QubesOS/qubes-issues/issues/1861
https://github.com/QubesOS/qubes-issues/issues/3585
https://github.com/QubesOS/qubes-issues/issues/6289

**Comment by e6lk7dqzm83p** [comment] 2021-09-25 06:26
Hi,

I don't think those are the issues...dom0 seem to be unable to find the repository to install the files (I think). If the repo is still up, I don't see why dom0 shouldn't be able to find it (which may be a Qubes R4.1 Beta issue?); if it's not up, I'll close this and ask @elliotkillick to update qvm-create-windows-qube.

I should note that previously I had success deploying the qvm-create-windows-qube tool (https://github.com/elliotkillick/qvm-create-windows-qube)---which is dependent on Qubes Windows Tools---subsequent to those issues (except 6289).

**Comment by awokd** [comment] 2021-11-07 21:15
Per the above, QWT for 4.1 does not yet exist, so closing for now.

**Comment by e6lk7dqzm83p** [comment] 2021-11-11 18:47
Hi,

Is there any plan to support QWT for Qubes 4.1 (which is currently in Beta)?

Thanks!

**Comment by awokd** [comment] 2021-11-14 16:31
>Is there any plan to support QWT for Qubes 4.1 (which is currently in Beta)?

Definitely, thanks for the catch. Will reopen this until QWT for 4.1 can be tested with the agreeable excellent tools by @elliotkillick, and documentation updated if needed.

**Comment by e6lk7dqzm83p** [comment] 2021-12-21 05:56
Hi,

I kind of got QWT installed via https://github.com/tabit-pro/qubes-windows-tools-cross; however nothing works (moving files to/from VMs, copy and past to/from VMs, attaching devices)

**Comment by awokd** [comment] 2022-03-29 18:19
Please see updated documentation at https://github.com/Qubes-Community/Contents/blob/master/docs/os/windows/windows-tools41.md.

**Closed by awokd** 2022-03-29 18:19 UTC
